apiVersion: v1
kind: Service
metadata:
  name: react-app-bago
spec:
  type: NodePort
  selector:
    app: react-app-bago
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 5172
      nodePort: 30486
